services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dwes
      MYSQL_USER: dwes
      MYSQL_PASSWORD: dwes
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/crearBBDD.sql:/docker-entrypoint-initdb.d/1_crearBBDD.sql
      - ./mysql/InsertarDatos.sql:/docker-entrypoint-initdb.d/2_InsertarDatos.sql
      - ./mysql/crearBBDDwordpress.sql:/docker-entrypoint-initdb.d/3_crearBBDDwordpress.sql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: dwes
      WORDPRESS_DB_PASSWORD: dwes
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html/
    networks:
        - app_network

  apache:
    build: apache/
    container_name: apache
    restart: always
    depends_on:
      - mysql
      - wordpress
    networks:
      - app_network
    ports:
      - "80:80"
    volumes:
      - proyecto:/var/www/html/

  php:
    build: php/
    container_name: php
    restart: always
    depends_on:
      - mysql
      - wordpress
    networks:
      - app_network
    ports:
      - "9000:9000"
    volumes:
      - proyecto:/var/www/html/

  wordpress-cli:
    image: wordpress:cli
    container_name: wordpress-cli
    depends_on:
      - mysql
      - wordpress
      - apache
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: dwes
      WORDPRESS_DB_PASSWORD: dwes
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
    entrypoint: >
      sh -c '
      echo "Esperamos unos segundos para dar tiempo de que todo se ponga en marcha";
      sleep 15;
      echo "Configurando WordPress en http://localhost:8080...";
      wp core install --url="http://localhost:8080" --title="Docker automatizado en multicontenedores" --admin_user="dwes" --admin_password="dwes" --admin_email="ajaio@birt.eus" --allow-root;
      echo "WordPress ha sido configurado correctamente en http://localhost:8080";
      exit;
      '
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  proyecto:
  mysql_data:
  wordpress_data: